import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // Prisma Client is generated during build and is not application source.
    "src/generated/**",
    "next-env.d.ts",
    // Compiled test output regenerated by `npm run test:unit` (tsc).
    ".test-output/**",
  ]),
]);

export default eslintConfig;
